import Config

config :trarecord, Trarecord.Repo,
  username: "postgres",
  password: "postgres",
  database: "trarecord_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

if Mix.target() == :ios do
  config :trarecord, Trarecord.Repo, hostname: "127.0.0.1"
end

if Mix.target() == :android do
  config :trarecord, Trarecord.Repo, hostname: "10.0.2.2"
end

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :trarecord, TrarecordWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Trarecord.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
