name: CI

on:
  pull_request:
    paths-ignore:
      - ".gitignore"
      - "README.md"
  push:
    branches:
      - "main"
    paths-ignore:
      - ".gitignore"
      - "README.md"


jobs:
  test: 
    name: Build & Test
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Seup Erlang & Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '26.2.5'
          elixir-version: '1.17.2'
      - name: Cache deps and _build
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}      

      - name: Install Dependencies      
        run: mix deps.get

      - name: Compiles without warnings
        run: mix compile --warnings-as-errors

      - name: Run Test
        run: mix test